// Notebook export — produces both .ipynb (Jupyter) and self-contained interactive .html.
import type { Dataset } from "./stats";
import type { Role } from "@/store/dataset-context";
import type { SnapshotBundle } from "./dashboard-store";
import { correlationMatrix, topCorrelations } from "./stats";

interface Cell {
  cell_type: "markdown" | "code";
  source: string[];
  metadata?: Record<string, unknown>;
  outputs?: unknown[];
  execution_count?: null;
}

function md(s: string): Cell {
  return {
    cell_type: "markdown",
    metadata: {},
    source: s.split("\n").map((l, i, arr) => (i < arr.length - 1 ? l + "\n" : l)),
  };
}
function code(s: string): Cell {
  return {
    cell_type: "code",
    metadata: {},
    execution_count: null,
    outputs: [],
    source: s.split("\n").map((l, i, arr) => (i < arr.length - 1 ? l + "\n" : l)),
  };
}

const ROLE_NOTES: Record<Role, { goal: string; modeling: string; extra: string[] }> = {
  data_analyst: {
    goal: "Profile, segment, and visualise the dataset for reporting.",
    modeling: "Skip ML — use group-bys, time series, and pivot tables.",
    extra: [
      "# Pivot example\n# df.pivot_table(index='<segment>', values=numeric_cols, aggfunc=['mean','sum']).round(2)",
    ],
  },
  business_analyst: {
    goal: "Translate the dataset into KPIs, drivers, and segment performance.",
    modeling: "Use regression for driver analysis; cohort tables for retention.",
    extra: [
      "# KPI example\n# df.groupby('<segment>').agg(revenue=('amount','sum'), orders=('id','count'), aov=('amount','mean')).round(2)",
    ],
  },
  data_scientist: {
    goal: "Hypothesis-driven analysis: distributions, relationships, feature ideas.",
    modeling: "Try Ridge / RF / GradientBoosting baselines with CV; add SHAP for interpretation.",
    extra: [
      "# SHAP\n# import shap; explainer = shap.TreeExplainer(pipe.named_steps['model']); shap.summary_plot(explainer.shap_values(X_t), X_t)",
    ],
  },
  ml_engineer: {
    goal: "Production-ready features: leakage checks, scaling, encoding, cross-val.",
    modeling: "Wrap everything in sklearn.Pipeline; persist with joblib; track with MLflow.",
    extra: [
      "# Persist\n# import joblib; joblib.dump(pipe.fit(X, y), 'model.joblib')",
      "# Drift monitoring\n# from scipy.stats import ks_2samp\n# for c in num_f: print(c, ks_2samp(X_train[c], X_new[c]).pvalue)",
    ],
  },
  ai_engineer: {
    goal: "Find text-rich columns, build embeddings, and design eval pairs.",
    modeling: "Use sentence-transformers for embeddings; FAISS for retrieval; LLM-judge for eval.",
    extra: [
      "# Embeddings\n# from sentence_transformers import SentenceTransformer\n# model = SentenceTransformer('all-MiniLM-L6-v2')\n# embeddings = model.encode(df['<text_col>'].astype(str).tolist(), show_progress_bar=True)",
      "# Retrieval\n# import faiss, numpy as np\n# index = faiss.IndexFlatIP(embeddings.shape[1]); index.add(embeddings.astype('float32'))",
    ],
  },
  data_engineer: {
    goal: "Validate schema, contracts, and pipeline reliability.",
    modeling: "Use Great Expectations / pandera for contracts; add freshness + uniqueness checks.",
    extra: [
      "# pandera schema\n# import pandera as pa\n# schema = pa.DataFrameSchema({c: pa.Column(df[c].dtype) for c in df.columns})\n# schema.validate(df)",
    ],
  },
};

export function buildIpynb(ds: Dataset, role: Role): string {
  const num = ds.profiles.filter((p) => p.type === "numeric").map((p) => p.name);
  const cat = ds.profiles.filter((p) => p.type === "categorical").map((p) => p.name);
  const target = num[num.length - 1] ?? "target";
  const safeName = ds.name.replace(/'/g, "\\'");
  const note = ROLE_NOTES[role];

  const cells: Cell[] = [
    md(
      `# 📊 ${ds.name} — Analysis Notebook\n\n**Generated by DataIQ Pro** for role: \`${role}\`\n\n**Goal:** ${note.goal}\n\n- Rows: **${ds.rowCount.toLocaleString()}** · Columns: **${ds.colCount}**\n- ML Readiness: **${ds.readinessScore}/100**\n- Missing cells: **${ds.missingTotal.toLocaleString()}** · Duplicate rows: **${ds.duplicateRows}**`,
    ),
    md(`## 1. Setup`),
    code(
      `import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\n\nsns.set_theme(style="whitegrid", palette="viridis")\npd.set_option("display.max_columns", None)\nplt.rcParams["figure.figsize"] = (10, 5)`,
    ),
    md(`## 2. Load dataset\n\nReplace the path with your local copy of \`${ds.name}\`.`),
    code(`df = pd.read_csv('${safeName}')\nprint(f"Shape: {df.shape}")\ndf.head()`),
    md(`## 3. Schema & missing values`),
    code(
      `print("=== Dtypes ===")\nprint(df.dtypes)\nprint("\\n=== Missing per column ===")\nprint(df.isnull().sum().sort_values(ascending=False))`,
    ),
    md(`## 4. Descriptive statistics`),
    code(
      `numeric_cols = ${JSON.stringify(num)}\ndf[numeric_cols].describe(percentiles=[.05,.25,.5,.75,.95]).T`,
    ),
    md(`## 5. Distributions`),
    code(
      `for col in numeric_cols[:6]:\n    fig, axes = plt.subplots(1, 2, figsize=(12, 3))\n    sns.histplot(df[col].dropna(), kde=True, ax=axes[0])\n    axes[0].set_title(f"{col} — distribution")\n    sns.boxplot(x=df[col].dropna(), ax=axes[1])\n    axes[1].set_title(f"{col} — boxplot")\n    plt.tight_layout(); plt.show()`,
    ),
    md(`## 6. Correlation matrix`),
    code(
      `if len(numeric_cols) >= 2:\n    plt.figure(figsize=(10, 8))\n    sns.heatmap(df[numeric_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm", center=0, square=True)\n    plt.title("Pearson correlation")\n    plt.tight_layout(); plt.show()`,
    ),
    md(`## 7. Categorical columns`),
    code(
      `categorical_cols = ${JSON.stringify(cat)}\nfor col in categorical_cols[:5]:\n    print(f"\\n=== {col} (top 10) ===")\n    print(df[col].value_counts().head(10))`,
    ),
    md(`## 8. Outlier detection (IQR rule)`),
    code(
      `def iqr_outliers(s):\n    q1, q3 = s.quantile([0.25, 0.75])\n    iqr = q3 - q1\n    lo, hi = q1 - 1.5*iqr, q3 + 1.5*iqr\n    return ((s < lo) | (s > hi)).sum(), lo, hi\n\nfor col in numeric_cols:\n    n, lo, hi = iqr_outliers(df[col].dropna())\n    pct = n / max(1, df[col].notna().sum()) * 100\n    print(f"{col:25s} outliers={n:>5d} ({pct:5.1f}%)  bounds=[{lo:.2f}, {hi:.2f}]")`,
    ),
    md(
      `## 9. End-to-end cleaning pipeline\n\nDeduplicate → trim/normalize text → impute → cap outliers → drop constants. Reproducible and idempotent.`,
    ),
    code(
      `from sklearn.impute import SimpleImputer\n\ndef clean(df_in: pd.DataFrame) -> pd.DataFrame:\n    df = df_in.copy()\n    # 1. drop exact duplicates\n    df = df.drop_duplicates().reset_index(drop=True)\n    # 2. trim + lowercase string columns\n    str_cols = df.select_dtypes(include='object').columns\n    for c in str_cols:\n        df[c] = df[c].astype(str).str.strip().str.lower().replace({'nan': np.nan, '': np.nan})\n    # 3. impute\n    num_cols = df.select_dtypes(include=np.number).columns.tolist()\n    cat_cols = [c for c in df.columns if c not in num_cols]\n    if num_cols:\n        df[num_cols] = SimpleImputer(strategy='median').fit_transform(df[num_cols])\n    if cat_cols:\n        df[cat_cols] = SimpleImputer(strategy='most_frequent').fit_transform(df[cat_cols])\n    # 4. cap outliers (IQR)\n    for c in num_cols:\n        q1, q3 = df[c].quantile([0.25, 0.75])\n        iqr = q3 - q1\n        df[c] = df[c].clip(q1 - 1.5*iqr, q3 + 1.5*iqr)\n    # 5. drop constant cols\n    nunique = df.nunique(dropna=False)\n    df = df.drop(columns=nunique[nunique <= 1].index.tolist())\n    return df\n\ndf_clean = clean(df)\nprint('Before:', df.shape, '→ After:', df_clean.shape)\ndf_clean.head()`,
    ),
    md(
      `## 10. Role-tailored ML / analysis pipeline\n\n${note.modeling}\n\nTarget candidate: \`${target}\` (last numeric column). Adjust as needed.`,
    ),
    code(
      `from sklearn.model_selection import train_test_split, cross_val_score, KFold\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\nfrom sklearn.linear_model import Ridge\nfrom sklearn.metrics import r2_score, mean_absolute_error\n\nTARGET = '${target}'\nif TARGET in df_clean.columns:\n    y = df_clean[TARGET]\n    X = df_clean.drop(columns=[TARGET])\n    num_f = X.select_dtypes(include=np.number).columns.tolist()\n    cat_f = X.select_dtypes(exclude=np.number).columns.tolist()\n    pre = ColumnTransformer([\n        ("num", StandardScaler(), num_f),\n        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_f),\n    ])\n    cv = KFold(n_splits=5, shuffle=True, random_state=42)\n    results = {}\n    for name, model in {"ridge": Ridge(), "rf": RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42), "gbr": GradientBoostingRegressor(random_state=42)}.items():\n        pipe = Pipeline([("prep", pre), ("model", model)])\n        scores = cross_val_score(pipe, X, y, cv=cv, scoring="r2", n_jobs=-1)\n        results[name] = (scores.mean(), scores.std())\n        print(f"{name:8s}  CV R²={scores.mean():+.4f} ± {scores.std():.4f}")\n    best = max(results, key=lambda k: results[k][0])\n    print(f"\\nBest baseline: {best}")\nelse:\n    print(f"⚠ Target {TARGET} not found — choose a different column")`,
    ),
    md(`## 11. Role extras — ${role.replace("_", " ")}`),
    ...note.extra.map((c) => code(c)),
    md(
      `---\n\n*Re-generate from DataIQ Pro after each new dataset upload to keep this notebook in sync.*`,
    ),
  ];

  return JSON.stringify(
    {
      cells,
      metadata: {
        kernelspec: { display_name: "Python 3", language: "python", name: "python3" },
        language_info: { name: "python", version: "3.11" },
        dataiq: { generated_at: new Date().toISOString(), role, dataset: ds.name },
      },
      nbformat: 4,
      nbformat_minor: 5,
    },
    null,
    1,
  );
}

// Compute the base64 SHA-256 hash of a string for CSP `'sha256-...'` sources.
// Works in the browser and in Node 18+ (both expose global crypto/btoa).
async function sha256Base64(text: string): Promise<string> {
  const bytes = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  const arr = new Uint8Array(digest);
  let bin = "";
  for (let i = 0; i < arr.length; i++) bin += String.fromCharCode(arr[i]);
  return btoa(bin);
}

export async function buildInteractiveHTML(
  ds: Dataset,
  role: Role,
  snapshots?: SnapshotBundle | null,
): Promise<string> {
  const corr = ds.correlation || correlationMatrix(ds);
  const top = topCorrelations(corr, 15);
  const num = ds.profiles.filter((p) => p.type === "numeric");
  const cat = ds.profiles.filter((p) => p.type === "categorical");

  // Build small histograms for top numeric columns (client-rendered with Chart.js via CDN).
  const histData = num.slice(0, 8).map((p) => {
    const vals = ds.rows.map((r) => Number(r[p.name])).filter((n) => !isNaN(n));
    let min = vals[0];
    let max = vals[0];
    for (let j = 1; j < vals.length; j++) {
      if (vals[j] < min) min = vals[j];
      if (vals[j] > max) max = vals[j];
    }
    const bins = 20;
    const w = (max - min) / bins || 1;
    const buckets = Array(bins).fill(0);
    for (const v of vals) buckets[Math.min(bins - 1, Math.floor((v - min) / w))]++;
    return {
      name: p.name,
      labels: buckets.map((_, i) => (min + i * w).toFixed(2)),
      counts: buckets,
    };
  });

  const colorFor = (r: number) => {
    const a = Math.min(1, Math.abs(r));
    return r >= 0 ? `hsl(0 70% ${95 - a * 40}%)` : `hsl(220 70% ${95 - a * 40}%)`;
  };

  const date = new Date().toLocaleString();
  const safeJSON = (v: unknown) => JSON.stringify(v).replace(/</g, "\\u003c");
  // HTML-escape user-controlled values before interpolating them into the markup.
  const esc = (v: unknown) =>
    String(v ?? "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");

  // All interactivity lives in this single vetted script. It is loaded under a
  // strict CSP that only allows scripts matching this exact SHA-256 hash (plus
  // the pinned Chart.js CDN), so any injected inline script is refused by the
  // browser. There are no inline event handlers anywhere in the document.
  const appScript = `
const RAW_ROWS = ${safeJSON(ds.rows.slice(0, 2000))};
const COLS = ${safeJSON(ds.columns)};
const HIST = ${safeJSON(histData)};

let filtered = RAW_ROWS;

function renderTable() {
  const tbody = document.querySelector('#data-table tbody');
  tbody.replaceChildren();
  filtered.slice(0, 500).forEach(r => {
    const tr = document.createElement('tr');
    COLS.forEach(c => {
      const td = document.createElement('td');
      // Use textContent so user-controlled cell values are never parsed as HTML.
      td.textContent = (r[c] == null ? '\u2014' : String(r[c]).slice(0, 80));
      tr.appendChild(td);
    });
    tbody.appendChild(tr);
  });
  document.getElementById('row-status').textContent = filtered.length.toLocaleString() + ' rows (showing ' + Math.min(500, filtered.length) + ')';
}

function applyFilter() {
  const col = document.getElementById('filter-col').value;
  const val = document.getElementById('filter-val').value.toLowerCase();
  if (!col || !val) { resetFilter(); return; }
  filtered = RAW_ROWS.filter(r => String(r[col] ?? '').toLowerCase().includes(val));
  renderTable();
}
function resetFilter() {
  document.getElementById('filter-val').value = '';
  filtered = RAW_ROWS;
  renderTable();
}

document.getElementById('nb-apply').addEventListener('click', applyFilter);
document.getElementById('nb-reset').addEventListener('click', resetFilter);

// Sortable stats table
document.querySelectorAll('#stats-table thead th, #data-table thead th').forEach((th, i) => {
  th.addEventListener('click', () => {
    const tbl = th.closest('table');
    const tbody = tbl.querySelector('tbody');
    const rows = [...tbody.querySelectorAll('tr')];
    const idx = [...th.parentNode.children].indexOf(th);
    const dir = th.dataset.dir === 'asc' ? 'desc' : 'asc';
    th.dataset.dir = dir;
    rows.sort((a,b) => {
      const av = a.children[idx].textContent.trim();
      const bv = b.children[idx].textContent.trim();
      const an = parseFloat(av), bn = parseFloat(bv);
      if (!isNaN(an) && !isNaN(bn)) return dir === 'asc' ? an-bn : bn-an;
      return dir === 'asc' ? av.localeCompare(bv) : bv.localeCompare(av);
    });
    rows.forEach(r => tbody.appendChild(r));
  });
});

// Render histograms
HIST.forEach((h, i) => {
  const ctx = document.getElementById('hist-' + i);
  if (!ctx) return;
  new Chart(ctx, {
    type: 'bar',
    data: { labels: h.labels, datasets: [{ label: h.name, data: h.counts, backgroundColor: 'rgba(124,58,237,.7)', borderRadius: 4 }] },
    options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: true, position: 'top' } }, scales: { x: { ticks: { maxRotation: 45, autoSkip: true, maxTicksLimit: 8 } } } }
  });
});

renderTable();
`;

  // Dashboard charts captured from the live BI dashboard. Only data: URLs are
  // embedded (the CSP allows img-src data: and nothing else), and every image
  // carries the verified aggregated series it was rendered from.
  const dashCharts = (snapshots?.charts ?? []).filter((c) => c.image.startsWith("data:image/"));
  const dashboardSection = dashCharts.length
    ? `<h2 id="dashboard">3b. Dashboard charts (captured ${esc(new Date(snapshots!.capturedAt).toLocaleString())})</h2>
<p class="meta">These images are exactly what was rendered on the DataIQ Pro dashboard, each with the verified aggregated data behind it.</p>
${dashCharts
  .map(
    (c) => `<div class="recs">
<h3>${esc(c.title)}</h3>
<img src="${esc(c.image)}" alt="${esc(c.title)}" style="width:100%;border-radius:.75rem;background:#0f172a" />
<p class="meta" style="margin:.6rem 0 .2rem"><strong>Caption:</strong> ${esc(c.caption)}</p>
${
  c.series.length
    ? `<details><summary>Verified data (${c.series.length} points)</summary>
<table><tr><th>Category</th><th>Value</th></tr>${c.series
        .slice(0, 60)
        .map((s) => `<tr><td>${esc(s.x)}</td><td>${esc(Number(s.y).toLocaleString())}</td></tr>`)
        .join("")}</table></details>`
    : ""
}
</div>`,
  )
  .join("")}`
    : "";

  const scriptHash = await sha256Base64(appScript);
  const csp = [
    "default-src 'none'",
    `script-src 'sha256-${scriptHash}' https://cdn.jsdelivr.net`,
    "style-src 'unsafe-inline'",
    "img-src data:",
    "font-src data:",
    "connect-src 'none'",
    "base-uri 'none'",
    "form-action 'none'",
    "frame-ancestors 'none'",
  ].join("; ");

  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="${csp}">
<title>${esc(ds.name)} — Interactive Notebook</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<style>
  *{box-sizing:border-box}
  body{font-family:system-ui,-apple-system,sans-serif;max-width:1180px;margin:0 auto;padding:2rem 1.5rem;color:#1a1a2e;background:#f7f8fb;line-height:1.55}
  h1{background:linear-gradient(135deg,#7c3aed,#06b6d4);-webkit-background-clip:text;color:transparent;font-size:2.5rem;margin:0 0 .25rem}
  h2{margin:2.5rem 0 1rem;font-size:1.4rem;border-bottom:2px solid #e5e7eb;padding-bottom:.4rem}
  h3{margin:1.5rem 0 .5rem;font-size:1.05rem;color:#4f46e5}
  .meta{color:#666;font-size:.9rem;margin-bottom:1rem}
  .toolbar{position:sticky;top:0;background:rgba(247,248,251,.95);backdrop-filter:blur(8px);padding:.75rem 0;margin:0 -1.5rem 1rem;padding:.75rem 1.5rem;z-index:10;border-bottom:1px solid #e5e7eb;display:flex;flex-wrap:wrap;gap:.5rem;align-items:center}
  .toolbar input,.toolbar select{padding:.4rem .6rem;border:1px solid #ddd;border-radius:.5rem;font-size:.85rem;background:white}
  .toolbar button{padding:.4rem .8rem;border:0;border-radius:.5rem;background:#7c3aed;color:white;font-weight:600;font-size:.85rem;cursor:pointer}
  .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:1rem;margin:1.5rem 0}
  .card{background:white;border-radius:1rem;padding:1rem;box-shadow:0 4px 14px rgba(0,0,0,.06)}
  .card .l{font-size:.7rem;color:#666;text-transform:uppercase;letter-spacing:.04em}
  .card .v{font-size:1.7rem;font-weight:700;margin-top:.2rem}
  table{width:100%;border-collapse:collapse;background:white;border-radius:.75rem;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.04);margin:.5rem 0}
  th,td{padding:.55rem .8rem;text-align:left;font-size:.85rem;border-bottom:1px solid #f0f0f0}
  th{background:#fafafa;font-weight:600;cursor:pointer;user-select:none}
  th.sorted::after{content:" ↕";opacity:.5}
  .heat td{text-align:center;font-family:monospace;font-size:.7rem;padding:.4rem}
  .pill{display:inline-block;padding:.15rem .5rem;border-radius:1rem;background:#eef2ff;color:#4f46e5;font-size:.7rem;font-weight:600}
  .grid2{display:grid;grid-template-columns:repeat(auto-fit,minmax(380px,1fr));gap:1rem}
  .chart-wrap{background:white;border-radius:.75rem;padding:.75rem;box-shadow:0 2px 8px rgba(0,0,0,.04);height:240px;position:relative}
  .toc{background:white;border-radius:.75rem;padding:1rem 1.5rem;box-shadow:0 2px 8px rgba(0,0,0,.04)}
  .toc a{color:#4f46e5;text-decoration:none;display:block;padding:.2rem 0}
  .toc a:hover{text-decoration:underline}
  footer{margin-top:3rem;padding:1rem;text-align:center;color:#999;font-size:.8rem}
  .recs{background:white;border-left:4px solid #7c3aed;padding:1rem 1.25rem;border-radius:.5rem;margin:.5rem 0}
  details{background:white;border-radius:.5rem;padding:.5rem 1rem;margin:.25rem 0}
  summary{font-weight:600;cursor:pointer;font-size:.9rem}
  pre{background:#0f172a;color:#f1f5f9;padding:1rem;border-radius:.5rem;overflow:auto;font-size:.78rem;line-height:1.5}
  code{font-family:ui-monospace,Menlo,monospace}
</style></head><body>

<h1>${esc(ds.name)}</h1>
<div class="meta">Interactive notebook · Generated ${date} · Role: <strong>${esc(role)}</strong></div>

<div class="toolbar">
  <strong style="font-size:.85rem">🔎 Filter rows:</strong>
  <select id="filter-col"><option value="">— column —</option>${ds.columns.map((c) => `<option>${esc(c)}</option>`).join("")}</select>
  <input id="filter-val" placeholder="contains…" />
  <button id="nb-apply" type="button">Apply</button>
  <button id="nb-reset" type="button" style="background:#666">Reset</button>
  <span id="row-status" style="margin-left:auto;font-size:.85rem;color:#666">${ds.rowCount.toLocaleString()} rows</span>
</div>

<nav class="toc">
  <strong>Contents</strong>
  <a href="#overview">1. Overview &amp; KPIs</a>
  <a href="#stats">2. Descriptive statistics</a>
  <a href="#dist">3. Distributions (interactive)</a>
  ${dashCharts.length ? `<a href="#dashboard">3b. Dashboard charts (captured)</a>` : ""}
  <a href="#corr">4. Correlation analysis</a>
  <a href="#cat">5. Categorical breakdown</a>
  <a href="#outliers">6. Outlier detection</a>
  <a href="#data">7. Data preview (sortable)</a>
  <a href="#code">8. Reproducible code</a>
  <a href="#recs">9. Recommendations</a>
</nav>


<h2 id="overview">1. Overview & KPIs</h2>
<div class="cards">
  <div class="card"><div class="l">Rows</div><div class="v">${ds.rowCount.toLocaleString()}</div></div>
  <div class="card"><div class="l">Columns</div><div class="v">${ds.colCount}</div></div>
  <div class="card"><div class="l">Numeric</div><div class="v">${num.length}</div></div>
  <div class="card"><div class="l">Categorical</div><div class="v">${cat.length}</div></div>
  <div class="card"><div class="l">Missing</div><div class="v">${ds.missingTotal.toLocaleString()}</div></div>
  <div class="card"><div class="l">Readiness</div><div class="v">${ds.readinessScore}/100</div></div>
</div>

<h2 id="stats">2. Descriptive statistics</h2>
<table id="stats-table"><thead><tr>
<th data-sort="name">Column</th><th data-sort="mean">Mean</th><th data-sort="median">Median</th><th data-sort="std">Std</th><th data-sort="min">Min</th><th data-sort="max">Max</th><th data-sort="skew">Skew</th><th data-sort="kurt">Kurt</th><th data-sort="missing">Missing</th>
</tr></thead><tbody>
${num.map((p) => `<tr><td><strong>${esc(p.name)}</strong></td><td>${p.mean?.toFixed(3)}</td><td>${p.median?.toFixed(3)}</td><td>${p.std?.toFixed(3)}</td><td>${p.min}</td><td>${p.max}</td><td>${p.skewness?.toFixed(2)}</td><td>${p.kurtosis?.toFixed(2)}</td><td>${p.missing} (${p.missingPct.toFixed(1)}%)</td></tr>`).join("")}
</tbody></table>

<h2 id="dist">3. Distributions</h2>
<div class="grid2">
${histData.map((h, i) => `<div class="chart-wrap"><canvas id="hist-${i}"></canvas></div>`).join("")}
</div>

${dashboardSection}



${
  corr.columns.length >= 2
    ? `<h2 id="corr">4. Correlation analysis</h2>
<h3>Top pairs</h3>
<table><tr><th>A</th><th>B</th><th>r</th></tr>
${top.map((t) => `<tr><td>${esc(t.a)}</td><td>${esc(t.b)}</td><td><strong style="color:${t.r >= 0 ? "#dc2626" : "#2563eb"}">${t.r.toFixed(3)}</strong></td></tr>`).join("")}
</table>
<h3>Matrix</h3>
<table class="heat"><tr><th></th>${corr.columns.map((c) => `<th>${esc(c)}</th>`).join("")}</tr>
${corr.matrix.map((row, i) => `<tr><th>${esc(corr.columns[i])}</th>${row.map((v) => `<td style="background:${colorFor(v)}">${v.toFixed(2)}</td>`).join("")}</tr>`).join("")}
</table>`
    : ""
}

${
  cat.length
    ? `<h2 id="cat">5. Categorical breakdown</h2>
${cat
  .slice(0, 8)
  .map(
    (p) => `<details><summary>${esc(p.name)} <span class="pill">${p.unique} unique</span></summary>
<table><tr><th>Value</th><th>Count</th></tr>${(p.topValues ?? [])
      .slice(0, 15)
      .map((t) => `<tr><td>${esc(t.value)}</td><td>${t.count}</td></tr>`)
      .join("")}</table>
</details>`,
  )
  .join("")}`
    : ""
}

<h2 id="outliers">6. Outlier detection</h2>
<table><tr><th>Column</th><th>IQR outliers</th><th>%</th><th>Z-score outliers</th><th>Bounds</th></tr>
${num.map((p) => `<tr><td>${esc(p.name)}</td><td>${p.outliersIQR}</td><td>${p.count ? (((p.outliersIQR ?? 0) / p.count) * 100).toFixed(1) : 0}%</td><td>${p.outliersZ}</td><td>[${p.iqrLower?.toFixed(2)}, ${p.iqrUpper?.toFixed(2)}]</td></tr>`).join("")}
</table>

<h2 id="data">7. Data preview</h2>
<div style="overflow:auto;max-height:500px"><table id="data-table"><thead><tr>${ds.columns.map((c, i) => `<th data-col="${i}">${esc(c)}</th>`).join("")}</tr></thead><tbody></tbody></table></div>

<h2 id="code">8. Reproducible code</h2>
<details><summary>Python — load & profile</summary>
<pre><code>import pandas as pd
df = pd.read_csv('${esc(ds.name.replace(/'/g, "\\'"))}')
print(df.shape)
print(df.describe(include='all').T)
print(df.isnull().sum())</code></pre>
</details>

<h2 id="recs">9. Recommendations</h2>
<div class="recs"><strong>Data quality:</strong> ${ds.duplicateRows > 0 ? `Drop ${ds.duplicateRows} duplicate rows. ` : ""}${ds.missingTotal > 0 ? "Impute missing values. " : ""}${num.filter((p) => Math.abs(p.skewness ?? 0) > 1).length ? "Apply log/sqrt transforms to highly-skewed columns. " : ""}${num.filter((p) => (p.outliersIQR ?? 0) / Math.max(1, p.count) > 0.05).length ? "Winsorize columns with >5% outliers." : "Outlier rates within tolerance."}</div>
<div class="recs"><strong>Modeling:</strong> Top correlated pairs are strong feature candidates. Standardize numerics, one-hot encode categoricals.</div>

<footer>Generated by <strong>DataIQ Pro</strong> · Interactive notebook for ${esc(role)}</footer>

<script>${appScript}</script>
</body></html>`;
}
