/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransformRouteImport } from './routes/transform'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ExportRouteImport } from './routes/export'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CodegenRouteImport } from './routes/codegen'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicInsightsHealthRouteImport } from './routes/api/public/insights-health'

const TransformRoute = TransformRouteImport.update({
  id: '/transform',
  path: '/transform',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CodegenRoute = CodegenRouteImport.update({
  id: '/codegen',
  path: '/codegen',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInsightsHealthRoute = ApiPublicInsightsHealthRouteImport.update({
  id: '/api/public/insights-health',
  path: '/api/public/insights-health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/audit': typeof AuditRoute
  '/charts': typeof ChartsRoute
  '/codegen': typeof CodegenRoute
  '/cookies': typeof CookiesRoute
  '/export': typeof ExportRoute
  '/guide': typeof GuideRoute
  '/overview': typeof OverviewRoute
  '/prep': typeof PrepRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/train': typeof TrainRoute
  '/transform': typeof TransformRoute
  '/api/public/insights-health': typeof ApiPublicInsightsHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/audit': typeof AuditRoute
  '/charts': typeof ChartsRoute
  '/codegen': typeof CodegenRoute
  '/cookies': typeof CookiesRoute
  '/export': typeof ExportRoute
  '/guide': typeof GuideRoute
  '/overview': typeof OverviewRoute
  '/prep': typeof PrepRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/train': typeof TrainRoute
  '/transform': typeof TransformRoute
  '/api/public/insights-health': typeof ApiPublicInsightsHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/audit': typeof AuditRoute
  '/charts': typeof ChartsRoute
  '/codegen': typeof CodegenRoute
  '/cookies': typeof CookiesRoute
  '/export': typeof ExportRoute
  '/guide': typeof GuideRoute
  '/overview': typeof OverviewRoute
  '/prep': typeof PrepRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/train': typeof TrainRoute
  '/transform': typeof TransformRoute
  '/api/public/insights-health': typeof ApiPublicInsightsHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/audit'
    | '/charts'
    | '/codegen'
    | '/cookies'
    | '/export'
    | '/guide'
    | '/overview'
    | '/prep'
    | '/privacy'
    | '/terms'
    | '/train'
    | '/transform'
    | '/api/public/insights-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/audit'
    | '/charts'
    | '/codegen'
    | '/cookies'
    | '/export'
    | '/guide'
    | '/overview'
    | '/prep'
    | '/privacy'
    | '/terms'
    | '/train'
    | '/transform'
    | '/api/public/insights-health'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/audit'
    | '/charts'
    | '/codegen'
    | '/cookies'
    | '/export'
    | '/guide'
    | '/overview'
    | '/prep'
    | '/privacy'
    | '/terms'
    | '/train'
    | '/transform'
    | '/api/public/insights-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AuditRoute: typeof AuditRoute
  ChartsRoute: typeof ChartsRoute
  CodegenRoute: typeof CodegenRoute
  CookiesRoute: typeof CookiesRoute
  ExportRoute: typeof ExportRoute
  GuideRoute: typeof GuideRoute
  OverviewRoute: typeof OverviewRoute
  PrepRoute: typeof PrepRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrainRoute: typeof TrainRoute
  TransformRoute: typeof TransformRoute
  ApiPublicInsightsHealthRoute: typeof ApiPublicInsightsHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transform': {
      id: '/transform'
      path: '/transform'
      fullPath: '/transform'
      preLoaderRoute: typeof TransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codegen': {
      id: '/codegen'
      path: '/codegen'
      fullPath: '/codegen'
      preLoaderRoute: typeof CodegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/insights-health': {
      id: '/api/public/insights-health'
      path: '/api/public/insights-health'
      fullPath: '/api/public/insights-health'
      preLoaderRoute: typeof ApiPublicInsightsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AuditRoute: AuditRoute,
  ChartsRoute: ChartsRoute,
  CodegenRoute: CodegenRoute,
  CookiesRoute: CookiesRoute,
  ExportRoute: ExportRoute,
  GuideRoute: GuideRoute,
  OverviewRoute: OverviewRoute,
  PrepRoute: PrepRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrainRoute: TrainRoute,
  TransformRoute: TransformRoute,
  ApiPublicInsightsHealthRoute: ApiPublicInsightsHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
