// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_URL
      ? import.meta.env.VITE_SUPABASE_URL
      : process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;

  const SUPABASE_PUBLISHABLE_KEY =
    typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY
      ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
      : process.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    console.warn(`[Supabase] Unconfigured or missing env vars: ${missing.join(", ")}.`);

    // Safe fallback stub client to avoid throwing uncaught runtime/SSR exceptions
    const dummyClient = {
      auth: {
        getSession: async () => ({ data: { session: null }, error: null }),
        getClaims: async () => ({ data: null, error: new Error("Supabase is not configured") }),
        onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      },
      from: () => ({
        select: () => dummyClient.from(),
        insert: async () => ({ data: null, error: new Error("Supabase is not configured") }),
        update: async () => ({ data: null, error: new Error("Supabase is not configured") }),
        delete: async () => ({ data: null, error: new Error("Supabase is not configured") }),
        eq: () => dummyClient.from(),
        ilike: () => dummyClient.from(),
        order: () => dummyClient.from(),
        limit: () => dummyClient.from(),
        gte: () => dummyClient.from(),
        lte: () => dummyClient.from(),
      }),
    };
    return dummyClient as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    try {
      if (!_supabase) _supabase = createSupabaseClient();
      return Reflect.get(_supabase, prop, receiver);
    } catch (e) {
      console.warn("[Supabase] Failed to access client property:", prop, e);
      return () => Promise.resolve({ data: null, error: e });
    }
  },
});

