// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    console.warn(`[Supabase Admin] Missing environment variable(s): ${missing.join(", ")}.`);

    const dummyAdmin = {
      from: () => ({
        select: () => dummyAdmin.from(),
        insert: async () => ({ data: null, error: new Error("Supabase admin client unconfigured") }),
        update: async () => ({ data: null, error: new Error("Supabase admin client unconfigured") }),
        delete: async () => ({ data: null, error: new Error("Supabase admin client unconfigured") }),
        eq: () => dummyAdmin.from(),
        ilike: () => dummyAdmin.from(),
        order: () => dummyAdmin.from(),
        limit: () => dummyAdmin.from(),
        gte: () => dummyAdmin.from(),
        lte: () => dummyAdmin.from(),
      }),
    };
    return dummyAdmin as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    try {
      if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
      return Reflect.get(_supabaseAdmin, prop, receiver);
    } catch (e) {
      console.warn("[Supabase Admin] Failed to access property:", prop, e);
      return () => Promise.resolve({ data: null, error: e });
    }
  },
});

